### ISSUE TITLE
Feature: add a 'skipSSR' property

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/code-split-component#10]
Some components have such heavy JavaScript powered controls, so prerendering them may frustrate a user as they will be unable to interact with the component until the scripts are loaded. In these cases wrap the component with CodeSplit and set the skipSSR prop. This will ensure that the component doesn't get prerendered on the server and will async load on client.

A nice compromise.

**Comment by ctrlplusb** [comment]
Alternative names for this property: 

 - defer
 - deferToClient
 - clientOnly

**Comment by developit** [comment]
`<CodeSplit defer />` is really nice, or `lazy` but technically its always a lazy load.

**Comment by swernerx** [comment]
I like 'defer', too.

**Comment by swernerx** [comment]
I'm just not sure if that's a case for CodeSplit. I mean having a generic way to post-pone rendering of specific parts might be useful. Independent from the actual routing/code splitting.

```
<Defer>
  <MyClientComponent/>
</Defer>
```

**Comment by ctrlplusb** [comment]
Great comment @swernerx 

Definitely something to consider.  We could start building an SSR toolkit.

**Comment by ctrlplusb** [comment]
Staged in new version.

_(yet to be released)_
