### ISSUE TITLE
Cleaning up usage with react router v4

### ISSUE THREAD

**Issue by xzilja** [ctrlplusb/code-split-component#13]
Hey,

I'm really glad I got a chance to stumble upon this project it didn't take to long to figure it out either and I was able to set up route based code splitting in the following way:

```
        <Match
          exactly pattern="/" component={() => (
            <CodeSplit chunkName="base" modules={{ Base: require('./layouts/Base') }}>
              { ({ Base }) => Base ? <Base /> : <div>Loading...</div> }
            </CodeSplit>
          )}
        /> 
```

And it now loads correct chunks for each route :) however I can't help and feel that this is a bit verbose, plus throws a coupe of errors in eslint like `no-confusing-arrow` for `({ Base }) => Base..` bit, and I don't want to disable it every time with a comment. I tried creating a whole new component that uses routers Match and CodeSplit, but failed, hence wanted to get your advice on this to see if it is possible to get some advice on this

Me being me and submitting this issue pre-maturely I just scrolled to the end of the read me and saw advised implementation for react router

```
<Match
  pattern="/about"
  render={routerProps =>
    <CodeSplit chunkName="about" modules={{ About: require('./About') }}>
      { ({ About }) => About && <About {...routerProps} /> }
    </CodeSplit>
  }
/>
```

Could you please explain where `routerProps` are coming from?

**Comment by dlebedynskyi** [comment]
@IljaDaderko  check this one https://react-router.now.sh/Match 
It is coming from react-router v4. You basically either need to set up component or user render to actually render a match. I prefer render for code-split stuff, but both are valid

**Comment by xzilja** [comment]
@dlebedynskyi any reason you prefer render over component?

**Comment by dlebedynskyi** [comment]
@IljaDaderko 

```
component={() => (
            <CodeSplit chunkName="base" modules={{ Base: require('./layouts/Base') }}>
```

you lost props supplied by router.  you basically rendered a functional component.
otherwise it is a preference - in component pass real component. in render - function to render conditional component. Code split as above.

**Comment by xzilja** [comment]
@dlebedynskyi I see, thank you :) I think this issue answers most of my questions and judging by future plans there is already a cleaner integration for react-royter v4 on its way. closing it.
