### ISSUE TITLE
How to use without <CodeSplit> being a Wrapper ?

### ISSUE THREAD

**Issue by SunnyGurnani** [ctrlplusb/code-split-component#16]
Is there a way to return the Actual Component instead of Wrapping the component within <CodeSplit> because when using isomorphic-relay-router the Component has to be a RelayContainer 

So Instead of 
```
  <CodeSplit chunkName="home" modules={{ Home: require('./components/App/Home') }}>
     { ({ Home }) => Home && <Home {...routerProps} /> }
   </CodeSplit>
```

Something like this
```
const Home = CodeSplit({chunkName="home", modules={{ Home: require('./components/App/Home') }});
return <Home {...routerProps} />
```

**Comment by ctrlplusb** [comment]
Hmmm, I am not familiar with relay or the isomorphic-relay-router, but off hand I can't think of why this wouldn't work.  On the server side the async behaviour of CodeSplit is disabled, so it should just end up resolving your component with the relay routing attached.

**Comment by ctrlplusb** [comment]
Project has been deprecated. 💖
