### ISSUE TITLE
Should use new import() API instead of System.import()

### ISSUE THREAD

**Issue by swernerx** [ctrlplusb/code-split-component#17]
Next beta of Webpack 2.1 is introducing support for the new TC-3 agreed `import()` syntax.

See: https://github.com/tc39/proposal-dynamic-import

I think the code split logic could benefit from the improvements made there over the usage of `System.import`.

**Comment by ctrlplusb** [comment]
Agreed! :)

**Comment by dlebedynskyi** [comment]
it looks like a really good proposal. This could also help avoid `require('../containers/Register')` syntax for modules. (not a fan of having require in middle of page). import as suggested in spec looks more organic here.

**Comment by ctrlplusb** [comment]
Closing in favour of #27
