### ISSUE TITLE
NOTIFICATION: HUGE NON-BREAKING UPDATE COMING

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/code-split-component#18]
I have been writing loads of unit tests and have uncovered all sorts of bugs.

Just pinging an update here so people know I am working on things.

**Comment by swernerx** [comment]
Maybe you have some time to look at this issue: https://github.com/mzgoddard/hard-source-webpack-plugin/issues/51#issuecomment-265066995

IMHO HardSource is by far more interesting than all the other build accelerates... at least in my first tests.

**Comment by dlebedynskyi** [comment]
@ctrlplusb would it make sense to create a milestone tracking for this? So that we could know when and what to expect in next release
