### ISSUE TITLE
PostCSS imports being swallowed

### ISSUE THREAD

**Issue by TylerK** [ctrlplusb/code-split-component#19]
Hello! Running into an issue whereby any CSS files imported via `import './styles.css'` are being mishandled by the `CodeSplit` component. Here is a Gist of my setup, could definitely use some help here: https://gist.github.com/TylerK/0b6e5464403846497558b580d9f62b12

Everything else is working perfectly though! :)

**Comment by swernerx** [comment]
Interesting. I am using PostCSS, too - so this would be pretty interesting if there is any bug. I don't had any issue yet. Do you use CSS modules in the CSS loader? Maybe sharing the loader specification for CSS files would help.

**Comment by TylerK** [comment]
@swernerx Sure thing, I've added my Webpack config to the Gist. An interesting point: When logging out the imported `.css` files I get an empty object (as expected) in any component that is _not_ a child of a `CodeSplit` component. 

When logging out the `.css` import from any `CodeSplit` child component, it will return an array with the following shape: 

```
[
  {
    0: <chunk hash string>
    1: <stringified css file>
  }
]
```

**Comment by ctrlplusb** [comment]
I have a feeling that the change being implemented for #20 may solve this issue too.

**Comment by ctrlplusb** [comment]
@TylerK could you please test this again with the latest alpha release?

**Comment by ctrlplusb** [comment]
Project has been deprecated. 💖
