### ISSUE TITLE
Test with AggressiveMergingPlugin

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/code-split-component#21]
https://github.com/ctrlplusb/react-universally/issues/170

**Comment by ctrlplusb** [comment]
@kikoanis - do you have an example repo for me to test this with?

It appears to be working with my latest changes, but perhaps it's just because no aggressive merging is happening (I am just using the base of react-universally)

**Comment by ctrlplusb** [comment]
@kikoanis - alpha.3 released.  Can you please retest this.

**Comment by kikoanis** [comment]
@ctrlplusb Will retest when I get home and let you know

**Comment by ctrlplusb** [comment]
Great :-)

There is an alpha.4 release too :-)

**Comment by kikoanis** [comment]
OK. So I tested it using alpha.4 and a fork of [react-universally](https://github.com/kikoanis/react-universally)   and I am afraid I do not see any changes. Here are my results
```
with buttons
	about 133 kb
	home  133 kb
	index 231 kb
Without buttons
	about 717 b
	home 815 b
	index 231 kb
mixed
	about with buttons 133 kb
	home without buttons 815 b
	index 231 kb
mixed 
	about without buttons 717 b
	home with buttons 133kb 
	index 231 kb
```
You can play with this using the above fork. I updated the build script a little bit to spit out build results.

**Comment by ctrlplusb** [comment]
Brilliant, thanks for the example.

To be honest I wasn't hopeful that the issue was resolved, but didn't have a proper case with which to test it.  Thank you for this!

**Comment by ctrlplusb** [comment]
Project has been deprecated. 💖

**Comment by ctrlplusb** [comment]
Please let me know your experiences with the new lib if you try it. I am confident you won't experience this issue any more.
