### ISSUE TITLE
Why serialize-javascript is peer? 

### ISSUE THREAD

**Issue by dlebedynskyi** [ctrlplusb/code-split-component#22]
```
npm WARN code-split-component@2.0.0-alpha.4 requires a peer of serialize-javascript@^1.3.0 but none was installed.
```

**Comment by ctrlplusb** [comment]
I need it for an internals requirement of binding a map object to the globals.  This allows me to know what the webpack generated ids are for modules/bundles.

**Comment by ctrlplusb** [comment]
So I serialise this to object.

**Comment by ctrlplusb** [comment]
But thinking about it now. The object is super simple and comes from me, so actually a JSON.stringify will do!

**Comment by ctrlplusb** [comment]
I'll change this.

**Comment by dlebedynskyi** [comment]
I don't mind lib. but if it is in - make it dependency not peer one. If you can get away without it, sure - ditch it.
