### ISSUE TITLE
React Hot Loader support

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/code-split-component#24]
Ok, so it looks like webpack HMR comparability is ok, but React Hot Loader not so. I get full page app re-renders, ala standard hot module reloading. I have some intuition for a "fix". Hopefully it works. Less config complexity will be nice.

**Comment by ctrlplusb** [comment]
Oooooh, just had a great idea :)

**Comment by slightlytyler** [comment]
@ctrlplusb in the future will `react-hot-loader` and `code-split-component`be able to work alongside each other? I'm only including the babel/webpack plugins in prod so HMR is working fine in dev for me but would love to be able to debug code splitting issues at the same time

**Comment by ctrlplusb** [comment]
@slightlytyler I hope so yes. :)

**Comment by ctrlplusb** [comment]
P.S. I've had two failed experiments and a look into the internals of RHL.  I am not optimistic in getting this working without a lot of hacking. In my opinion it just isn't worth the complexity it could bring into this project.

**Comment by ctrlplusb** [comment]
Project has been deprecated. 💖

**Comment by ctrlplusb** [comment]
Works in my new lib. No hacks.
