### ISSUE TITLE
Sync mode names with webpacks targets

### ISSUE THREAD

**Issue by swernerx** [ctrlplusb/code-split-component#26]
Webpack uses either `node` or `web` as a target for typical SSR apps. I figure it would make sense to sync the options in this plugin to use the same convention. 

Naming is already hard enough and we use a ton of tools nowadays. We should align on some basics patterns to not confuse new users.

Docs: https://webpack.js.org/configuration/target/#target

BTW: I am in progress of changing this in advanced-boilerplate and prepublish-lib, too.

**Comment by ctrlplusb** [comment]
Project has been deprecated. 💖
