### ISSUE TITLE
CodeSplit doesn't work with nested routes in RR4

### ISSUE THREAD

**Issue by diondirza** [ctrlplusb/code-split-component#28]
I have setup nested routes for my app, and i got this error when navigate to it if I use CodeSplit inside render props of Match.

usage: 
```
<Match
  pattern={`${pathname}/accept`}
  render={routerProps =>
    <CodeSplit chunkName="payment" modules={{ AccPage: require('./accept') }}>
      { ({ AccPage }) => AccPage && <AccPage {...routerProps} />
  }
/>
```
Error in console:
```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Subscriber`.
printWarning @ __dev_vendor_dll__.js:4694
__dev_vendor_dll__.js:4647 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Subscriber`.
    at invariant (__dev_vendor_dll__.js:4640)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (__dev_vendor_dll__.js:35856)
    at ReactCompositeComponentWrapper._updateRenderedComponent (__dev_vendor_dll__.js:33666)
    at ReactCompositeComponentWrapper._performComponentUpdate (__dev_vendor_dll__.js:33629)
    at ReactCompositeComponentWrapper.updateComponent (__dev_vendor_dll__.js:33550)
    at ReactCompositeComponentWrapper.receiveComponent (__dev_vendor_dll__.js:33452)
    at Object.receiveComponent (__dev_vendor_dll__.js:7576)
    at ReactCompositeComponentWrapper._updateRenderedComponent (__dev_vendor_dll__.js:33659)
    at ReactCompositeComponentWrapper._performComponentUpdate (__dev_vendor_dll__.js:33629)
    at ReactCompositeComponentWrapper.updateComponent (__dev_vendor_dll__.js:33550)
```
Any idea how to make this work guys? Without codesplit it works perfectly?

**Comment by teonik** [comment]
Did you try

```
<Match
  pattern={`${pathname}/accept`}
  render={routerProps =>
    <CodeSplit chunkName="payment" modules={{ AccPage: require('./accept') }}>
      { ({ AccPage }) => AccPage ? <AccPage {...routerProps}  : <div>Loading...</div> />
  }
/>
```
or something similar?
In your code the route will return null while the chunk is loading so the warning you see is React trying to tell that that.

**Comment by diondirza** [comment]
@teonik Your code seems promising, yet still no luck so far.
Here is my final code:
```
<Match
  pattern={`${pathname}/accept`}
  render={routerProps =>
    <CodeSplit chunkName="payment" modules={{ AccPage: require('./accept') }}>
      { ({ AccPage }) => (AccPage ? <AccPage {...routerProps} /> : <div>Loading...</div>) }
    </CodeSplit>
  }
/>
```
Yet it still produce same error. Have you got it working on your end?

**Comment by teonik** [comment]
I use exactly the same setup and it's working.How do you export your AccPage component?It should be exported as default from your './accept.js' module.
For example
```
export default class AccPage ...
```
instead of 
```
export class AccPage ...
```
If you prefer to use the latter you can try
```
<CodeSplit modules={{ AccPage: require('./accept').AccPage }} ... />
```
but i haven't tested it

**Comment by ctrlplusb** [comment]
@diondirza any more feedback on this? If you are still experiencing it I am happy to give it a shot. 👍

**Comment by diondirza** [comment]
@ctrlplusb yes, still having this issue, have followed what teonik said yet still produced same result. I will try to reproduce this in clean react universally project.

**Comment by ctrlplusb** [comment]
Okay sorry to hear. This library is back in my sight so hopefully can help out soon.

**Comment by diondirza** [comment]
@ctrlplusb I got no problem if I used clean react-universally project with nested route in it, yet if I try with react universally that has been integrated with many libraries in it (my current project) seems it won't work. Does it because I used decorator for MobX? Really strange...

**Comment by ctrlplusb** [comment]
Hey @diondirza 

Hmm, it's hard to say without seeing your setup.  I would try remove things one by one and see when it starts working again.  Let me know if you find the culprit.

**Comment by diondirza** [comment]
@ctrlplusb, I have made a [branch](https://github.com/diondirza/react-universally/tree/bug-code-split) that can reproduce this issue by using my current setup using react universally. Maybe you can help me find the culprit this time, please take a look.

Try navigate to /about/info and you'll see the bug there.

**Comment by ctrlplusb** [comment]
Typo 😀

You are doing this:

```js
import CodeSplit from 'code-split-component';
```

Should be:

```js
import { CodeSplit } from 'code-split-component';
```

Check your page sub components. 👌

**Comment by diondirza** [comment]
OMG, what a dumb of my eyes for all this time never realize that typo.
Thanks a lot dude, that's was really fast. 😀

**Comment by ctrlplusb** [comment]
Haha, don't worry about it.  It happens to us all! 😀

**Comment by teonik** [comment]
@diondirza Great 👍
