### ISSUE TITLE
Remove "node" requirement to ~6.7.0

### ISSUE THREAD

**Issue by bkniffler** [ctrlplusb/code-split-component#4]
Yarn will fail if version 6.9.1 is installed. You could either use ^ (don't forget to adapt for 7.x.x) or remove the requirement.

**Comment by ctrlplusb** [comment]
Yeah, I've heard yarn is going to make us all respect the engine config. :)

I need to make some time to review yarn and then figure out what would be the most appropriate configuration.

**Comment by viktorbezdek** [comment]
I'd suggest just setting node version engine support following semver scheme `^6.7.0` as @bkniffler pointed out.
