### ISSUE TITLE
Does it work with React Router 3?

### ISSUE THREAD

**Issue by volkanunsal** [ctrlplusb/code-split-component#5]
I want to try this out, but it seems to require using React Router 4, which is still in alpha. Can I use RR3 instead?

**Comment by ctrlplusb** [comment]
You could try create a higher order function that takes in a natural route component and enhances it with the `CodeSplit` component?

**Comment by ctrlplusb** [comment]
To be clear. It doesn't have any dependency on any routing library. You can use the component independently of them.  I will try update the docs to be clearer on this.

**Comment by ctrlplusb** [comment]
Please note issue #7 - any router implementation will suffer until I make this change.

**Comment by ctrlplusb** [comment]
closing in favour of #8
